<<<<<<< HEAD
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"  # Persistent volume for Postgres data
    ports:
      - "5432:5432"
=======
version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    networks:
      - pg-network
>>>>>>> 7c52cc6 (Dockerizing the ingestion process)

  pgadmin:
    image: dpage/pgadmin4
    environment:
<<<<<<< HEAD
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_conn_data:/var/lib/pgadmin:rw"  # Persistent volume for pgAdmin
    ports:
      - "8080:80"

volumes:
  pgadmin_conn_data:  # Volume to persist pgAdmin connections
  ny_taxi_postgres_data:  # Volume to persist Postgres database
=======
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
>>>>>>> 7c52cc6 (Dockerizing the ingestion process)
